"""Simulate minute-by-minute synthetic yield curves with a VAR(n) model.

The VAR is applied to yield changes, and yields are obtained by cumulatively
summing those changes. Its target covariance is the covariance generated by
the companion three-factor PPCA model (level, slope, curvature plus noise).

Rates are decimals (0.04 means 4%). Volatility inputs are annualised basis
points. By default, the output grid contains every calendar minute, 24/7.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence

import numpy as np
import pandas as pd
from scipy.signal import lfilter


TENORS = np.array([1, 2, 3, 5, 7, 10, 12, 15, 20, 30], dtype=float)
COLUMNS = ["1y", "2y", "3y", "5y", "7y", "10y", "12y", "15y", "20y", "30y"]

DEFAULT_INITIAL_CURVE = np.array(
    [0.0400, 0.0390, 0.0385, 0.0380, 0.0382,
     0.0390, 0.0395, 0.0400, 0.0410, 0.0420],
    dtype=float,
)


def _period_start(period: str, end: pd.Timestamp) -> pd.Timestamp:
    """Interpret ``min`` as minutes and ``m`` as calendar months."""
    match = re.fullmatch(r"\s*(\d+)\s*(min|h|d|w|m|y)\s*", period.lower())
    if match is None:
        raise ValueError(
            "period must look like '30min', '12h', '10d', '2w', '3m', or '5y'"
        )

    amount = int(match.group(1))
    unit = match.group(2)
    if amount <= 0:
        raise ValueError("period must be strictly positive")

    if unit == "min":
        return end - pd.Timedelta(minutes=amount)
    if unit == "h":
        return end - pd.Timedelta(hours=amount)
    if unit == "d":
        return end - pd.Timedelta(days=amount)
    if unit == "w":
        return end - pd.Timedelta(weeks=amount)
    if unit == "m":
        return end - pd.DateOffset(months=amount)
    return end - pd.DateOffset(years=amount)


def make_factor_loadings(tenors: np.ndarray = TENORS) -> pd.DataFrame:
    """Return level, slope and curvature loading shapes."""
    tenors = np.asarray(tenors, dtype=float)
    if tenors.ndim != 1 or len(tenors) < 3 or np.any(tenors <= 0):
        raise ValueError("tenors must be a one-dimensional array of positive values")

    log_tenor = np.log(tenors)
    x = 2.0 * (log_tenor - log_tenor.min()) / np.ptp(log_tenor) - 1.0

    level = np.ones_like(x)
    slope = x.copy()
    raw_curvature = 1.0 - x**2

    base = np.column_stack((level, slope))
    curvature = raw_curvature - base @ np.linalg.lstsq(
        base, raw_curvature, rcond=None
    )[0]

    loadings = np.column_stack((level, slope, curvature))
    loadings /= np.max(np.abs(loadings), axis=0)

    return pd.DataFrame(
        loadings,
        index=[f"{tenor:g}y" for tenor in tenors],
        columns=["level", "slope", "curvature"],
    )


def ppca_change_covariance(
    *,
    factor_vols_bp: Sequence[float] = (70.0, 45.0, 30.0),
    noise_vol_bp: float = 10.0,
    weekdays_only: bool = False,
) -> pd.DataFrame:
    """Return the target one-minute PPCA covariance of yield changes."""
    factor_vols = np.asarray(factor_vols_bp, dtype=float)
    if (
        factor_vols.shape != (3,)
        or not np.all(np.isfinite(factor_vols))
        or np.any(factor_vols < 0)
    ):
        raise ValueError("factor_vols_bp must contain three non-negative values")
    if not np.isfinite(noise_vol_bp) or noise_vol_bp < 0:
        raise ValueError("noise_vol_bp must be non-negative")

    annual_minutes = (252.0 if weekdays_only else 365.25) * 24.0 * 60.0
    sqrt_dt = np.sqrt(1.0 / annual_minutes)
    bp_to_decimal = 1.0e-4

    loadings = make_factor_loadings(TENORS).to_numpy()
    w = loadings * (factor_vols * bp_to_decimal * sqrt_dt)
    noise_sd = noise_vol_bp * bp_to_decimal * sqrt_dt
    covariance = w @ w.T + np.eye(len(COLUMNS)) * noise_sd**2

    return pd.DataFrame(covariance, index=COLUMNS, columns=COLUMNS)


def make_lag_weights(n: int, lag_decay: float = 0.70) -> np.ndarray:
    """Return positive, geometrically declining weights that sum to one."""
    if isinstance(n, bool) or not isinstance(n, (int, np.integer)) or n < 1:
        raise ValueError("n must be a positive integer")
    if not np.isfinite(lag_decay) or not 0.0 < lag_decay <= 1.0:
        raise ValueError("lag_decay must lie in (0, 1]")

    weights = lag_decay ** np.arange(n, dtype=float)
    return weights / weights.sum()


def _ar_variance_multiplier(coefficients: np.ndarray) -> float:
    """Unconditional AR(n) variance when innovation variance equals one."""
    coefficients = np.asarray(coefficients, dtype=float)
    n = len(coefficients)

    # Yule--Walker equations for gamma(0), ..., gamma(n).
    system = np.zeros((n + 1, n + 1), dtype=float)
    rhs = np.zeros(n + 1, dtype=float)
    system[0, 0] = 1.0
    system[0, 1:] = -coefficients
    rhs[0] = 1.0

    for lag in range(1, n + 1):
        system[lag, lag] += 1.0
        for k, coefficient in enumerate(coefficients, start=1):
            system[lag, abs(lag - k)] -= coefficient

    gamma_zero = np.linalg.solve(system, rhs)[0]
    if not np.isfinite(gamma_zero) or gamma_zero <= 0:
        raise ValueError("could not obtain a valid stationary variance")
    return float(gamma_zero)


def _spectral_radius(coefficients: np.ndarray) -> float:
    """Return the spectral radius of an AR companion matrix."""
    n = len(coefficients)
    companion = np.zeros((n, n), dtype=float)
    companion[0] = coefficients
    if n > 1:
        companion[1:, :-1] = np.eye(n - 1)
    return float(np.max(np.abs(np.linalg.eigvals(companion))))


def _coerce_initial_curve(
    initial_curve: Sequence[float] | Mapping[str, float] | pd.Series | None,
) -> np.ndarray:
    if initial_curve is None:
        values = DEFAULT_INITIAL_CURVE.copy()
    elif isinstance(initial_curve, (Mapping, pd.Series)):
        missing = [column for column in COLUMNS if column not in initial_curve]
        if missing:
            raise ValueError(f"initial_curve is missing tenors: {missing}")
        values = np.array([initial_curve[column] for column in COLUMNS], dtype=float)
    else:
        values = np.asarray(initial_curve, dtype=float)

    if values.shape != (len(COLUMNS),):
        raise ValueError(f"initial_curve must contain exactly {len(COLUMNS)} rates")
    if not np.all(np.isfinite(values)):
        raise ValueError("initial_curve must contain only finite values")
    return values


def _build_mode_ar_coefficients(
    n: int,
    persistence: float,
    lag_decay: float,
    dimension: int,
) -> np.ndarray:
    """Build stationary AR(n) coefficients for the covariance eigenmodes.

    The dominant three modes receive successively lower persistence. The
    residual PPCA-noise modes share one still-lower persistence, making their
    definition invariant to rotations within an equal-eigenvalue subspace.
    """
    if not np.isfinite(persistence) or not 0.0 <= persistence < 1.0:
        raise ValueError("persistence must lie in [0, 1)")

    lag_weights = make_lag_weights(n, lag_decay)
    multipliers = np.full(dimension, 0.25)
    multipliers[: min(3, dimension)] = np.array([1.0, 0.80, 0.60])[:dimension]
    total_persistence = persistence * multipliers
    return total_persistence[:, None] * lag_weights[None, :]


def var_coefficient_matrices(
    n: int,
    *,
    persistence: float = 0.20,
    lag_decay: float = 0.70,
    factor_vols_bp: Sequence[float] = (70.0, 45.0, 30.0),
    noise_vol_bp: float = 10.0,
    weekdays_only: bool = False,
) -> np.ndarray:
    """Return the dense coefficient matrices A_1, ..., A_n of the VAR(n)."""
    target_covariance = ppca_change_covariance(
        factor_vols_bp=factor_vols_bp,
        noise_vol_bp=noise_vol_bp,
        weekdays_only=weekdays_only,
    ).to_numpy()
    eigenvalues, eigenvectors = np.linalg.eigh(target_covariance)
    order = np.argsort(eigenvalues)[::-1]
    eigenvectors = eigenvectors[:, order]

    mode_coefficients = _build_mode_ar_coefficients(
        n, persistence, lag_decay, len(COLUMNS)
    )
    return np.stack(
        [
            (eigenvectors * mode_coefficients[:, lag]) @ eigenvectors.T
            for lag in range(n)
        ]
    )


def simulate_yield_curve_var(
    period: str,
    n: int = 1,
    *,
    end: str | pd.Timestamp | None = None,
    initial_curve: Sequence[float] | Mapping[str, float] | pd.Series | None = None,
    factor_vols_bp: Sequence[float] = (70.0, 45.0, 30.0),
    noise_vol_bp: float = 10.0,
    persistence: float = 0.20,
    lag_decay: float = 0.70,
    volatility_match: str = "one_minute",
    weekdays_only: bool = False,
    timezone: str = "UTC",
    seed: int | None = None,
    burn_in: int | None = None,
    chunk_size: int = 100_000,
) -> pd.DataFrame:
    """Simulate a VAR(n) process for yield changes and integrate it to yields.

    Parameters
    ----------
    period:
        History length, such as ``"3m"`` or ``"5y"``. Here ``m`` means
        calendar months and ``min`` means minutes.
    n:
        VAR order. For example, ``n=5`` uses five lags of one-minute changes.
    end:
        Final timestamp. If omitted, use the current time.
    initial_curve:
        Ten decimal yields in ``COLUMNS`` order, or a mapping keyed by those
        column names.
    factor_vols_bp, noise_vol_bp:
        The same annualised PPCA volatility parameters used by the companion
        PPCA generator. These determine the target covariance.
    persistence:
        Sum of the lag coefficients for the dominant covariance mode. Other
        modes use 80%, 60% and 25% of this value. Must be in [0, 1).
    lag_decay:
        Geometric decay applied across the n lags. A value below one gives more
        weight to recent lags.
    volatility_match:
        ``"one_minute"`` matches the PPCA unconditional covariance of
        one-minute changes. ``"long_run"`` instead matches the long-run
        covariance rate of cumulative yield changes.
    weekdays_only:
        False gives a continuous 24/7 one-minute index. True keeps every minute
        Monday through Friday and omits weekends.
    timezone, seed, chunk_size:
        As in the PPCA generator.
    burn_in:
        Number of unreturned observations used to reach stationarity. If None,
        choose a conservative value from n and the VAR spectral radius.

    Returns
    -------
    pandas.DataFrame
        Decimal yields with a timezone-aware DatetimeIndex named ``datestamp``
        and columns 1y through 30y.

    Notes
    -----
    In the covariance eigenbasis, each mode follows its own stationary AR(n).
    Transforming back produces dense 10-by-10 VAR coefficient matrices. The
    levels remain non-stationary because they are cumulative sums of stationary
    VAR changes, as requested.
    """
    if isinstance(n, bool) or not isinstance(n, (int, np.integer)) or n < 1:
        raise ValueError("n must be a positive integer")
    if volatility_match not in {"one_minute", "long_run"}:
        raise ValueError("volatility_match must be 'one_minute' or 'long_run'")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be strictly positive")

    if end is None:
        end_ts = pd.Timestamp.now(tz=timezone).floor("min")
    else:
        end_ts = pd.Timestamp(end)
        if end_ts.tzinfo is None:
            end_ts = end_ts.tz_localize(timezone)
        else:
            end_ts = end_ts.tz_convert(timezone)
        end_ts = end_ts.floor("min")

    start_ts = _period_start(period, end_ts)
    index = pd.date_range(start=start_ts, end=end_ts, freq="min")
    if weekdays_only:
        index = index[index.dayofweek < 5]
    index.name = "datestamp"
    if len(index) == 0:
        raise ValueError("the selected period contains no timestamps on the chosen grid")

    initial = _coerce_initial_curve(initial_curve)
    target_covariance = ppca_change_covariance(
        factor_vols_bp=factor_vols_bp,
        noise_vol_bp=noise_vol_bp,
        weekdays_only=weekdays_only,
    ).to_numpy()

    # Work in the covariance eigenbasis. This makes exact covariance
    # calibration a set of independent univariate AR(n) calculations.
    eigenvalues, eigenvectors = np.linalg.eigh(target_covariance)
    order = np.argsort(eigenvalues)[::-1]
    eigenvalues = np.maximum(eigenvalues[order], 0.0)
    eigenvectors = eigenvectors[:, order]

    mode_coefficients = _build_mode_ar_coefficients(
        n, persistence, lag_decay, len(COLUMNS)
    )
    variance_multipliers = np.array(
        [_ar_variance_multiplier(row) for row in mode_coefficients]
    )

    if volatility_match == "one_minute":
        innovation_variances = eigenvalues / variance_multipliers
    else:
        coefficient_sums = mode_coefficients.sum(axis=1)
        innovation_variances = eigenvalues * (1.0 - coefficient_sums) ** 2
    innovation_sds = np.sqrt(np.maximum(innovation_variances, 0.0))

    spectral_radii = np.array(
        [_spectral_radius(row) for row in mode_coefficients]
    )
    if np.any(spectral_radii >= 1.0):
        raise ValueError("the constructed VAR is not stationary")

    if burn_in is None:
        largest_radius = float(spectral_radii.max())
        mixing_burn = 0
        if largest_radius > 0:
            mixing_burn = int(np.ceil(np.log(1.0e-10) / np.log(largest_radius)))
        burn_in = max(1_000, 20 * n, mixing_burn)
    elif isinstance(burn_in, bool) or not isinstance(burn_in, (int, np.integer)):
        raise ValueError("burn_in must be a non-negative integer or None")
    elif burn_in < 0:
        raise ValueError("burn_in must be a non-negative integer or None")

    rng = np.random.default_rng(seed)
    filter_states = np.zeros((len(COLUMNS), n), dtype=float)

    def filter_modes(innovations: np.ndarray) -> np.ndarray:
        filtered = np.empty_like(innovations)
        for mode in range(len(COLUMNS)):
            denominator = np.r_[1.0, -mode_coefficients[mode]]
            filtered[:, mode], filter_states[mode] = lfilter(
                [1.0],
                denominator,
                innovations[:, mode],
                zi=filter_states[mode],
            )
        return filtered

    # Burn in the stationary changes without retaining the observations.
    burn_remaining = burn_in
    while burn_remaining > 0:
        count = min(chunk_size, burn_remaining)
        innovations = rng.standard_normal((count, len(COLUMNS))) * innovation_sds
        filter_modes(innovations)
        burn_remaining -= count

    rates = np.empty((len(index), len(COLUMNS)), dtype=float)
    rates[0] = initial
    current = initial.copy()

    write_at = 1
    while write_at < len(index):
        count = min(chunk_size, len(index) - write_at)
        innovations = rng.standard_normal((count, len(COLUMNS))) * innovation_sds
        mode_changes = filter_modes(innovations)
        changes = mode_changes @ eigenvectors.T

        block = current + np.cumsum(changes, axis=0)
        rates[write_at : write_at + count] = block
        current = block[-1]
        write_at += count

    result = pd.DataFrame(rates, index=index, columns=COLUMNS)
    result.attrs.update(
        {
            "model": f"VAR({n}) on yield changes",
            "var_order": int(n),
            "volatility_match": volatility_match,
            "persistence": float(persistence),
            "lag_decay": float(lag_decay),
        }
    )
    return result


if __name__ == "__main__":
    curves = simulate_yield_curve_var("5d", n=5, seed=42)
    print(curves.head())
    print(curves.tail())
    print(f"shape = {curves.shape}")
